### ISSUE TITLE
JSX ref

### ISSUE THREAD

**Issue by andreichuk** [fabiospampinato/voby#1]
Is JSX's 'ref' attribute supported? In the following example it does nothing:
```ts

// voby 0.16

const App = () => {
    let eInput;

    function onClick() {
        console.log("eInput: " + eInput); // outputs 'eInput: undefined'
    }

    return (
        <input type="text" ref={eInput} onClick={onClick}/>
    )
};

render(<App />, document.body);
```

**Comment by fabiospampinato** [comment]
It is supported, but it must be a function, which will be called with the node. So basically I'd recommend making that an observable.

The code you pasted can't possibly work, you are just passing `ref={undefined}` effectively, there's no way that variable could get assigned. It works in Solid only because its transform changes how the language works, you are not really writing plain JS anymore.
